In [2]:
import numpy as np
from typing import Union

In [8]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
C = np.array([[3, 2], [1, 0], [1, 2]])

In [15]:
# сложение
def addition(A: list[Union], B: list[Union]) -> list[Union]:
    if A.shape != B.shape:
        raise Exception("Wrong shape")
        
    result = A + B
    return result
print(addition(A, B))
print(addition(A, C))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


Exception: Wrong shape

In [17]:
def subtraction(A: list[Union], B: list[Union]) -> list[Union]:
    if A.shape != B.shape:
        raise Exception("Wrong shape")
        
    result = A - B
    return result
print(subtraction(A, B))
print(subtraction(A, C))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Exception: Wrong shape

In [21]:
def multiplication(*args) -> list[Union]:
    result = args[0]
    for arr in args[1:]:
        if result.shape[1] != arr.shape[0]:
            raise Exception("Wrong shape")
        result =  np.dot(result, arr)
    return result

print(multiplication(A, B))
print(multiplication(A, B, C))
D = np.array([[3, 2], [1, 0], [1, 2],[0, 0]])
print(multiplication(A, D))

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]
[[138 120]
 [300 264]
 [462 408]]


Exception: Wrong shape